import type { NvidiaModelConfig } from "./types.js";

/**
 * Embedding and Reranking Models (NVIDIA)
 */
export const EMBEDDING_MODELS: NvidiaModelConfig[] = [
  {
    id: "nvidia/nv-embed-v1",
    name: "NV-Embed v1",
    publisher: "NVIDIA",
    capabilities: ["embedding"],
    contextWindow: 512,
    costPerTokenInput: 0.01 / 1_000_000,
    costPerTokenOutput: 0,
    description: "Generates high-quality numerical embeddings from text inputs",
    bestFor: ["text embeddings", "semantic search", "RAG"],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: "nvidia/nv-embedqa-e5-v5",
    name: "NV-EmbedQA E5 v5",
    publisher: "NVIDIA",
    capabilities: ["embedding", "reranking"],
    contextWindow: 512,
    costPerTokenInput: 0.01 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "English text embedding model for question-answering retrieval",
    bestFor: ["QA retrieval", "English embeddings", "RAG"],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: "nvidia/llama-3_2-nemoretriever-300m-embed-v1",
    name: "NeMo Retriever 300M Embed v1",
    publisher: "NVIDIA",
    capabilities: ["embedding", "multilingual"],
    contextWindow: 512,
    costPerTokenInput: 0.005 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Multilingual, cross-lingual embedding model supporting 26 languages",
    bestFor: ["multilingual RAG", "cross-lingual search", "long-document QA"],
    supportsTools: false,
    supportsStreaming: false,
    languages: ["26 languages"],
  },
  {
    id: "nvidia/llama-3_2-nemoretriever-300m-embed-v2",
    name: "NeMo Retriever 300M Embed v2",
    publisher: "NVIDIA",
    capabilities: ["embedding", "multilingual"],
    contextWindow: 512,
    costPerTokenInput: 0.005 / 1_000_000,
    costPerTokenOutput: 0,
    description: "Enhanced multilingual embedding model with improved accuracy",
    bestFor: [
      "multilingual RAG",
      "cross-lingual search",
      "improved embeddings",
    ],
    supportsTools: false,
    supportsStreaming: false,
    languages: ["26 languages"],
  },
  {
    id: "nvidia/llama-3_2-nemoretriever-1b-vlm-embed-v1",
    name: "NeMo Retriever 1B VLM Embed v1",
    publisher: "NVIDIA",
    capabilities: ["embedding", "multimodal"],
    contextWindow: 512,
    costPerTokenInput: 0.015 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Multimodal question-answer retrieval representing queries as text and documents as images",
    bestFor: [
      "visual document retrieval",
      "multimodal RAG",
      "image+text search",
    ],
    multimodal: true,
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: "nvidia/llama-3.2-nv-embedqa-1b-v2",
    name: "NV-EmbedQA 1B v2",
    publisher: "NVIDIA",
    capabilities: ["embedding", "multilingual"],
    contextWindow: 512,
    costPerTokenInput: 0.02 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Multilingual and cross-lingual text QA retrieval with long context support",
    bestFor: ["QA retrieval", "long context", "multilingual search"],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: "nvidia/llama-3.2-nv-rerankqa-1b-v2",
    name: "NV-RerankQA 1B v2",
    publisher: "NVIDIA",
    capabilities: ["reranking", "multilingual"],
    contextWindow: 512,
    costPerTokenInput: 0.02 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Fine-tuned reranking model for multilingual text question-answering",
    bestFor: ["result reranking", "QA optimization", "search improvement"],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: "nvidia/llama-3.2-nemoretriever-500m-rerank-v2",
    name: "NeMo Retriever 500M Rerank v2",
    publisher: "NVIDIA",
    capabilities: ["reranking"],
    contextWindow: 512,
    costPerTokenInput: 0.01 / 1_000_000,
    costPerTokenOutput: 0,
    description: "GPU-accelerated model for passage relevance scoring",
    bestFor: ["passage ranking", "retrieval optimization", "RAG improvement"],
    supportsTools: false,
    supportsStreaming: false,
  },
];
