import type { NvidiaModelConfig } from './types.js';

/**
 * Kimi Models (Moonshot AI)
 */
export const KIMI_MODELS: NvidiaModelConfig[] = [
  {
    id: 'moonshotai/kimi-k2.5',
    name: 'Kimi K2.5',
    publisher: 'Moonshot AI',
    capabilities: [
      'chat',
      'code',
      'vision',
      'multimodal',
      'reasoning',
      'agentic',
      'long-context',
      'function-calling',
      'embedding',
    ],
    contextWindow: 256_000,
    costPerTokenInput: 0.6 / 1_000_000,
    costPerTokenOutput: 0.6 / 1_000_000,
    description: '1T parameter multimodal MoE for high-capacity video and image understanding',
    bestFor: ['multimodal tasks', 'video understanding', 'complex reasoning', 'agentic workflows'],
    parameters: '1T (MoE)',
    multimodal: true,
    moE: true,
    supportsTools: true,
    supportsStreaming: true,
    languages: ['en', 'zh', 'ja', 'ko', 'es', 'fr', 'de'],
  },
  {
    id: 'moonshotai/kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    publisher: 'Moonshot AI',
    capabilities: ['chat', 'reasoning', 'function-calling', 'long-context', 'agentic'],
    contextWindow: 256_000,
    costPerTokenInput: 0.6 / 1_000_000,
    costPerTokenOutput: 0.6 / 1_000_000,
    description: 'Open reasoning model with 256K context and enhanced tool use',
    bestFor: ['step-by-step reasoning', 'complex problem solving', 'agent tasks'],
    parameters: '1T (MoE)',
    moE: true,
    supportsTools: true,
    supportsStreaming: true,
  },
  {
    id: 'moonshotai/kimi-k2-instruct',
    name: 'Kimi K2 Instruct',
    publisher: 'Moonshot AI',
    capabilities: ['chat', 'code', 'reasoning', 'agentic', 'function-calling'],
    contextWindow: 256_000,
    costPerTokenInput: 0.6 / 1_000_000,
    costPerTokenOutput: 0.6 / 1_000_000,
    description: 'State-of-the-art open MoE model with strong reasoning and coding',
    bestFor: ['coding', 'complex reasoning', 'agentic applications'],
    parameters: '1T (MoE)',
    moE: true,
    supportsTools: true,
    supportsStreaming: true,
  },
  {
    id: 'moonshotai/kimi-k2-instruct-0905',
    name: 'Kimi K2 Instruct (0905)',
    publisher: 'Moonshot AI',
    capabilities: ['chat', 'code', 'reasoning', 'agentic', 'long-context', 'function-calling'],
    contextWindow: 512_000,
    costPerTokenInput: 0.7 / 1_000_000,
    costPerTokenOutput: 0.7 / 1_000_000,
    description: 'Enhanced version with longer context and advanced reasoning',
    bestFor: ['very long documents', 'advanced reasoning', 'agentic coding'],
    parameters: '1T (MoE)',
    moE: true,
    supportsTools: true,
    supportsStreaming: true,
  },
];
