import type { NvidiaModelConfig } from './types.js';

/**
 * Life Sciences Models (NVIDIA, MIT, OpenFold, IPD, ColabFold)
 */
export const LIFE_SCIENCES_MODELS: NvidiaModelConfig[] = [
  {
    id: 'nvidia/genmol-generate',
    name: 'GenMol',
    publisher: 'NVIDIA',
    capabilities: ['biology', 'chemistry', 'molecule-generation'],
    contextWindow: 512,
    costPerTokenInput: 0.2 / 1_000_000,
    costPerTokenOutput: 0.02 / 1_000_000,
    description: 'Fragment-based molecular generation by discrete diffusion',
    bestFor: ['drug discovery', 'molecule design', 'chemistry'],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: 'nvidia/molmim-generate',
    name: 'MolMIM',
    publisher: 'NVIDIA',
    capabilities: ['biology', 'chemistry', 'molecule-generation'],
    contextWindow: 512,
    costPerTokenInput: 0.25 / 1_000_000,
    costPerTokenOutput: 0.025 / 1_000_000,
    description: 'Controlled generation of molecules with desired properties',
    bestFor: ['property optimization', 'drug discovery', 'targeted molecules'],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: 'mit/diffdock',
    name: 'DiffDock',
    publisher: 'MIT',
    capabilities: ['biology', 'chemistry', 'docking'],
    contextWindow: 0,
    costPerTokenInput: 0.3 / 1_000_000,
    costPerTokenOutput: 0,
    description: 'Predicts 3D structure of molecular-protein interactions',
    bestFor: ['protein docking', 'drug-target interaction', 'structural biology'],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: 'mit/boltz2',
    name: 'Boltz-2',
    publisher: 'MIT',
    capabilities: ['biology', 'protein-folding'],
    contextWindow: 0,
    costPerTokenInput: 0.25 / 1_000_000,
    costPerTokenOutput: 0,
    description: 'Predicts complex biomolecular structures',
    bestFor: ['protein folding', 'structure prediction', 'structural biology'],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: 'openfold/openfold3',
    name: 'OpenFold3',
    publisher: 'OpenFold',
    capabilities: ['biology', 'protein-folding', 'drug-discovery'],
    contextWindow: 0,
    costPerTokenInput: 0.35 / 1_000_000,
    costPerTokenOutput: 0,
    description: 'Third-generation biomolecular foundation model for structure prediction',
    bestFor: ['protein complexes', 'drug discovery', 'biomolecular structures'],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: 'ipd/proteinmpnn',
    name: 'ProteinMPNN',
    publisher: 'IPD',
    capabilities: ['biology', 'protein-generation'],
    contextWindow: 0,
    costPerTokenInput: 0.2 / 1_000_000,
    costPerTokenOutput: 0,
    description: 'Deep learning for predicting amino acid sequences for protein backbones',
    bestFor: ['protein design', 'sequence prediction', 'synthetic biology'],
    supportsTools: false,
    supportsStreaming: false,
  },
  {
    id: 'colabfold/msa-search',
    name: 'MSA Search',
    publisher: 'ColabFold',
    capabilities: ['biology', 'sequence-alignment'],
    contextWindow: 0,
    costPerTokenInput: 0.15 / 1_000_000,
    costPerTokenOutput: 0,
    description: 'Generates multiple sequence alignment from query sequence and database',
    bestFor: ['sequence alignment', 'evolutionary analysis', 'protein research'],
    supportsTools: false,
    supportsStreaming: false,
  },
];
