import type { NvidiaModelConfig } from './types.js';

/**
 * Regional/Sovereign AI Models
 */
export const REGIONAL_MODELS: NvidiaModelConfig[] = [
  {
    id: 'stockmark/stockmark-2-100b-instruct',
    name: 'Stockmark 2 100B',
    publisher: 'Stockmark',
    capabilities: ['chat', 'text-generation', 'multilingual'],
    contextWindow: 128_000,
    costPerTokenInput: 0.45 / 1_000_000,
    costPerTokenOutput: 0.45 / 1_000_000,
    description: 'Japanese-specialized LLM for enterprise business documents',
    bestFor: ['Japanese business documents', 'enterprise Japan', 'sovereign AI'],
    parameters: '100B',
    supportsTools: true,
    supportsStreaming: true,
    languages: ['ja', 'en'],
  },
  {
    id: 'speakleash/bielik-11b-v2.6-instruct',
    name: 'Bielik 11B v2.6',
    publisher: 'SpeakLeash',
    capabilities: ['chat', 'text-generation', 'summarization'],
    contextWindow: 32_000,
    costPerTokenInput: 0.06 / 1_000_000,
    costPerTokenOutput: 0.06 / 1_000_000,
    description: 'State-of-the-art model for Polish language processing',
    bestFor: ['Polish language', 'Polish chatbots', 'sovereign AI (Poland)'],
    parameters: '11B',
    supportsTools: true,
    supportsStreaming: true,
    languages: ['pl', 'en'],
  },
  {
    id: 'opengpt-x/teuken-7b-instruct-commercial-v0.4',
    name: 'Teuken 7B Commercial',
    publisher: 'OpenGPT-X',
    capabilities: ['chat', 'text-generation', 'multilingual'],
    contextWindow: 32_000,
    costPerTokenInput: 0.04 / 1_000_000,
    costPerTokenOutput: 0.04 / 1_000_000,
    description: 'Multilingual 7B LLM instruction-tuned on all 24 EU languages',
    bestFor: ['EU languages', 'European applications', 'multilingual EU content'],
    parameters: '7B',
    supportsTools: true,
    supportsStreaming: true,
    languages: ['all 24 EU languages'],
  },
  {
    id: 'utter-project/eurollm-9b-instruct',
    name: 'EuroLLM 9B',
    publisher: 'Utter Project',
    capabilities: ['chat', 'text-generation', 'multilingual'],
    contextWindow: 32_000,
    costPerTokenInput: 0.05 / 1_000_000,
    costPerTokenOutput: 0.05 / 1_000_000,
    description: 'State-of-the-art multilingual model for all 24 EU languages',
    bestFor: ['EU sovereign AI', 'multilingual Europe', 'regional content'],
    parameters: '9B',
    supportsTools: true,
    supportsStreaming: true,
    languages: ['all 24 EU languages'],
  },
  {
    id: 'gotocompany/gemma-2-9b-cpt-sahabatai-instruct',
    name: 'SahabatAI Gemma 2 9B',
    publisher: 'Goto Company',
    capabilities: ['chat', 'text-generation', 'instruction-following'],
    contextWindow: 32_000,
    costPerTokenInput: 0.05 / 1_000_000,
    costPerTokenOutput: 0.05 / 1_000_000,
    description: 'Indonesian-specialized LLM with proficiency in local dialects',
    bestFor: ['Indonesian language', 'local dialects', 'Southeast Asia'],
    parameters: '9B',
    supportsTools: true,
    supportsStreaming: true,
    languages: ['id', 'en', 'local dialects'],
  },
];
