import type { NvidiaModelConfig } from "./types.js";

/**
 * Speech Models (NVIDIA)
 * - Speech-to-Text (ASR)
 * - Text-to-Speech (TTS)
 * - Translation
 */
export const SPEECH_MODELS: NvidiaModelConfig[] = [
  // ==================== SPEECH-TO-TEXT MODELS ====================
  {
    id: "nvidia/parakeet-tdt-0.6b-v2",
    name: "Parakeet TDT 0.6B",
    publisher: "NVIDIA",
    capabilities: ["speech-to-text"],
    contextWindow: 0,
    costPerTokenInput: 0.002 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Accurate and optimized English transcriptions with punctuation and timestamps",
    bestFor: ["English ASR", "word timestamps", "punctuation"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["en"],
  },
  {
    id: "nvidia/parakeet-ctc-0.6b-asr",
    name: "Parakeet CTC 0.6B ASR",
    publisher: "NVIDIA",
    capabilities: ["speech-to-text"],
    contextWindow: 0,
    costPerTokenInput: 0.002 / 1_000_000,
    costPerTokenOutput: 0,
    description: "Accurate English transcription with streaming support",
    bestFor: ["streaming ASR", "English speech", "real-time transcription"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["en"],
  },
  {
    id: "nvidia/parakeet-ctc-1.1b-asr",
    name: "Parakeet CTC 1.1B ASR",
    publisher: "NVIDIA",
    capabilities: ["speech-to-text"],
    contextWindow: 0,
    costPerTokenInput: 0.003 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Record-setting accuracy and performance for English transcription",
    bestFor: ["high-accuracy ASR", "batch transcription", "English audio"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["en"],
  },
  {
    id: "nvidia/parakeet-ctc-0.6b-zh-cn",
    name: "Parakeet CTC 0.6B Mandarin",
    publisher: "NVIDIA",
    capabilities: ["speech-to-text"],
    contextWindow: 0,
    costPerTokenInput: 0.002 / 1_000_000,
    costPerTokenOutput: 0,
    description: "Accurate and optimized Mandarin-English transcriptions",
    bestFor: ["Mandarin ASR", "Chinese speech", "bilingual transcription"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["zh-cn", "en"],
  },
  {
    id: "nvidia/parakeet-ctc-0.6b-zh-tw",
    name: "Parakeet CTC 0.6B Taiwanese",
    publisher: "NVIDIA",
    capabilities: ["speech-to-text"],
    contextWindow: 0,
    costPerTokenInput: 0.002 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Record-setting accuracy for Mandarin-Taiwanese-English transcriptions",
    bestFor: ["Taiwanese ASR", "Mandarin+Taiwanese", "regional Chinese"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["zh-tw", "zh-cn", "en"],
  },
  {
    id: "nvidia/parakeet-ctc-0.6b-es",
    name: "Parakeet CTC 0.6B Spanish",
    publisher: "NVIDIA",
    capabilities: ["speech-to-text"],
    contextWindow: 0,
    costPerTokenInput: 0.002 / 1_000_000,
    costPerTokenOutput: 0,
    description: "Accurate Spanish-English transcriptions with punctuation",
    bestFor: ["Spanish ASR", "bilingual transcription", "Hispanic markets"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["es", "en"],
  },
  {
    id: "nvidia/parakeet-ctc-0.6b-vi",
    name: "Parakeet CTC 0.6B Vietnamese",
    publisher: "NVIDIA",
    capabilities: ["speech-to-text"],
    contextWindow: 0,
    costPerTokenInput: 0.002 / 1_000_000,
    costPerTokenOutput: 0,
    description: "Accurate Vietnamese-English transcriptions with punctuation",
    bestFor: ["Vietnamese ASR", "Southeast Asia", "bilingual transcription"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["vi", "en"],
  },

  // ==================== TEXT-TO-SPEECH MODELS ====================
  {
    id: "nvidia/magpie-tts-flow",
    name: "Magpie TTS Flow",
    publisher: "NVIDIA",
    capabilities: ["text-to-speech"],
    contextWindow: 4_000,
    costPerTokenInput: 0.05 / 1_000_000,
    costPerTokenOutput: 0,
    description:
      "Expressive and engaging text-to-speech from short audio samples",
    bestFor: ["voice cloning", "expressive TTS", "brand voices"],
    supportsTools: false,
    supportsStreaming: true,
  },
  {
    id: "nvidia/magpie-tts-multilingual",
    name: "Magpie TTS Multilingual",
    publisher: "NVIDIA",
    capabilities: ["text-to-speech", "multilingual"],
    contextWindow: 4_000,
    costPerTokenInput: 0.06 / 1_000_000,
    costPerTokenOutput: 0,
    description: "Natural and expressive voices in multiple languages",
    bestFor: ["multilingual TTS", "voice agents", "global applications"],
    supportsTools: false,
    supportsStreaming: true,
    languages: ["en", "es", "fr", "de", "it", "ja", "zh", "ko"],
  },

  // ==================== TRANSLATION MODELS ====================
  {
    id: "nvidia/riva-translate-1.6b",
    name: "Riva Translate 1.6B",
    publisher: "NVIDIA",
    capabilities: ["translation"],
    contextWindow: 4_000,
    costPerTokenInput: 0.05 / 1_000_000,
    costPerTokenOutput: 0.05 / 1_000_000,
    description: "Smooth global interactions in 36 languages",
    bestFor: ["multilingual translation", "global communication", "NMT"],
    supportsTools: false,
    supportsStreaming: false,
    languages: ["36 languages"],
  },
  {
    id: "nvidia/riva-translate-4b-instruct-v1_1",
    name: "Riva Translate 4B Instruct v1.1",
    publisher: "NVIDIA",
    capabilities: ["translation"],
    contextWindow: 8_000,
    costPerTokenInput: 0.08 / 1_000_000,
    costPerTokenOutput: 0.08 / 1_000_000,
    description: "Translation in 12 languages with few-shot example capability",
    bestFor: [
      "instruction-based translation",
      "customizable NMT",
      "12 languages",
    ],
    supportsTools: false,
    supportsStreaming: false,
    languages: ["12 languages"],
  },
];
