# Codecov Configuration for G-Rump
# See: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        only_pulls: false
      
      backend:
        target: 80%
        threshold: 2%
        paths:
          - "backend/src/**"
        if_ci_failed: error
      
      frontend:
        target: 80%
        threshold: 2%
        paths:
          - "frontend/src/**"
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
      
      backend:
        target: 90%
        paths:
          - "backend/src/**"
      
      frontend:
        target: 80%
        paths:
          - "frontend/src/**"

  # Files/directories to ignore
  ignore:
    - "**/*.test.ts"
    - "**/*.test.tsx"
    - "**/*.test.js"
    - "**/*.spec.ts"
    - "**/tests/**"
    - "**/__tests__/**"
    - "**/__mocks__/**"
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/coverage/**"
    - "**/scripts/**"
    - "**/*.config.ts"
    - "**/*.config.js"
    - "**/*.d.ts"
    - "**/intent-compiler/**"
    - "**/docs/**"
    - "**/docs-site/**"

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "header, diff, flags, components, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false

flags:
  backend:
    paths:
      - backend/src/
    carryforward: true
    after_n_builds: 1
  
  frontend:
    paths:
      - frontend/src/
    carryforward: true
    after_n_builds: 1

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
  
  individual_components:
    - component_id: backend-core
      name: Backend Core
      paths:
        - backend/src/services/**
        - backend/src/routes/**
    
    - component_id: backend-middleware
      name: Backend Middleware
      paths:
        - backend/src/middleware/**
    
    - component_id: frontend-components
      name: Frontend Components
      paths:
        - frontend/src/components/**
        - frontend/src/lib/**
    
    - component_id: packages
      name: Shared Packages
      paths:
        - packages/*/src/**
